name: Python BMI-sekolahmu-Staging application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME_STAG: ${{ 'staging-cicd-sekolahmu' }}
  APP_NAME_PROD: ${{ 'cicd-sekolahmu' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 # this will check the python code for syntax errors/editing errors
      run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest #finally we will want to run our tests
      run: |
        pip install pytest
        pip install pytest-cov
        pytest

  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://staging-cicd-sekolahmu.herokuapp.com/?height=167&weight=70'
    steps:
      - name: checkout git
        uses: actions/checkout@v2
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      # Push the Docker image to Heroku Container Registry
      - name: Publish to Stag
        run: |
          heroku container:push web -a $APP_NAME_STAG
          heroku container:release web -a $APP_NAME_STAG

  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'https://cicd-sekolahmu.herokuapp.com/?height=167&weight=70'
    steps:
      - name: checkout git
        uses: actions/checkout@v2
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      # Push the Docker image to Heroku Container Registry
      - name: Publish to Prod
        run: |
          heroku container:push web -a $APP_NAME_PROD
          heroku container:release web -a $APP_NAME_PROD
